config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'tags#index'
  get '/tags/new' => 'tags#new'
  post 'tags' => 'tags#create'
  get '/tags/:id' => 'tags#show', as: :tag


  get 'tags/destinations/new' => 'destinations#new', as: :new_destination
  post 'destinations' => 'destinations#create'
  get 'destinations/:id' => 'destinations#show', as: :destination
  get 'destinations/:id/edit' => 'destinations#edit', as: :edit_destination
  patch '/destinations/:id' => 'destinations#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :destinations

  accepts_nested_attributes_for :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  def show
    @destination = Destination.find(params[:id])
    @tag = Tag.find(@destination.tag_id)
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(destination_params)
    if @destination.save
      redirect_to '/tags'
    else
      render 'new'
    end
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update_attributes(destination_params)
      redirect_to(:action => 'show', :id => @destination.id)
    else
      render 'edit'
    end
  end

  private
    def destination_params
      params.require(:destination).permit(:name, :description, :image, :tag_id)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @destinations = @tag.destinations
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to '/tags'
    else
      render 'new'
    end
  end

  private
    def tag_params
      params.require(:tag).permit(:title, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/destinations/edit.html.erb
<%= form_for(@destination) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_area :name %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.submit "Update" %>
<% end %>

app/views/destinations/new.html.erb
<%= form_for(@destination) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_area :name %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :image_url %><br>
  <%= f.text_area :image %><br>
  <%= f.hidden_field :tag_id, :value => params[:tag] %>
  <%= f.submit "Create" %>
<% end %>

app/views/destinations/show.html.erb
<%= image_tag("#{@destination.image}") %><br>
<%= @destination.name %><br>
<%= @destination.description %><br>
<%= link_to "See More", destination_path(@destination) %><br>
<%= link_to "Edit", edit_destination_path(@destination) %>

app/views/layouts/_nav-bar.html.erb
<div class="nav-bar">
    <% if @tag != nil %>
      <span style="float: left;"><%= @tag.title %></span>
      <span style="float: right;">
        <%= link_to 'New Destination', new_destination_path(tag: @tag.id) %>
      </span>
    <% else%>
    <span style="float: left;">has_many and belongs_to association app</span>
    <span style="float: right;"><%= link_to 'New Tag Category', '/tags/new' %></span>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav-bar' %>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<div class="card-row">
  <% @tags.each do |t| %>
    <div class="cards">
      <%= image_tag("#{t.image}") %><br>
      <%= t.title %><br>
      <%= link_to "Learn More", tag_path(t) %>
    </div>
  <% end %>
</div>

app/views/tags/new.html.erb
<%= form_for(@tag) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_area :title %><br>
  <%= f.label :image %><br>
  <%= f.text_area :image %><br>
  <%= f.submit "Create" %>
<% end %>

app/views/tags/show.html.erb
<div class="card-row">
  <% @destinations.each do |d| %>
    <div class="cards">
      <%= image_tag("#{d.image}") %><br>
      <%= d.name %><br>
      <%= link_to "See More", destination_path(d) %><br>
    </div>
  <% end %>
</div>